### ISSUE TITLE
Reschedule the task to run ASAP when task is fixed

### ISSUE THREAD

**Issue by golenkovm** [catalyst/moodle-tool_fix_delete_modules#10]
It looks like when `Permanently Delete Module #xxx` is clicked it fixes the task, but doesn't reset its `nextruntime` and `faildelay`. Thus, when `admin/tool/fix_delete_modules/index.php` is accessed the task may still be there with clickable `Permanently Delete Module #xxx`. The task should be reset to run ASAP as part of `$reporter->make_fix()` call.

**Comment by bradpasley** [comment]
This section of code does reset `nextruntime` and `faildelay`, although it doesn't execute the task: https://github.com/catalyst/moodle-tool_fix_delete_modules/blob/dev-objectoriented-35/classes/surgeon.php#L328-L339

If the task is executed in there, that would certainly prevent viewing the task again in `index.php`.

**Comment by golenkovm** [comment]
I debugged this and can see that this `if` returns `false`:
https://github.com/catalyst/moodle-tool_fix_delete_modules/blob/dev-objectoriented-35/classes/surgeon.php#L329

**Comment by bradpasley** [comment]
Does it return true for Moodle 4.0+? It's upgdated.

**Comment by golenkovm** [comment]
Have you had a chance to implement a unit test to make sure it's working?

**Comment by bradpasley** [comment]
Resolved with https://github.com/catalyst/moodle-tool_fix_delete_modules/pull/14
