### ISSUE TITLE
Plugin review

### ISSUE THREAD

**Issue by golenkovm** [catalyst/moodle-tool_fix_delete_modules#8]
Raising this as an issue to make sure comms won't get lost.

I had a look at the plugin code and there are some things that would need to be fixed/implemented before we send this plugin to production sites.

* [x] Functions in `lib.php` should be refactored into classes.
* [x] Once this is done they need to be covered with unit tests.
* [x] phpdocs should have proper description (in most cases it's just copied function name).
* [x] Plugin readme and unit tests should cover all potential scenarios this plugin can fix.
* [x] User facing pages (eg `index.php`, `delete_module.php`, `separate_module.php`) should have less logic. What can be moved to classes should be moved. This will let you cover various scenarios with unit tests as well.
* [x] Add the shared workflows.
* [x] Get it green.
* [x] (won't be done) I would recommend to introduce mustache templates and minimise HTML stuff in php.

**Comment by brendanheywood** [comment]
I'm gonna be a partial dissenting opinion. This tool is by its nature a bit of a hack, so it doesn't need to be gold plated.

Re unit tests - yes go for it. But things like mustache templates do not matter at all. The main point of mustache is to make it easier to author and to override in a theme and neither is relevant here.

**Comment by brendanheywood** [comment]
Also start with just adding the shared workflows in and get that green will go a long way for the basic code standards

**Comment by bradpasley** [comment]
Thanks for the feedback guys. I'll get on to making the lib into classes & build phpunit tests.

**Comment by bradpasley** [comment]
Will be closed with https://github.com/catalyst/moodle-tool_fix_delete_modules/pull/9

**Comment by bradpasley** [comment]
Thanks for the review Misha.
